# Generated by Django 4.0.6 on 2022-09-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='total',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
