# Generated by Django 4.0.6 on 2022-09-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_total_delete_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
