# Generated by Django 4.0.6 on 2022-09-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='a1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='a2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='a3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='a4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='a5',
            field=models.IntegerField(default=0),
        ),
    ]
