# Generated by Django 4.0.6 on 2022-10-25 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_a1_question_a2_question_a3_question_a4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='total',
        ),
    ]
