# Generated by Django 4.0.6 on 2022-07-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_othello',
            new_name='GameOthello',
        ),
        migrations.RenameModel(
            old_name='List_of_Games',
            new_name='GamesList',
        ),
        migrations.RenameModel(
            old_name='Game_tictactoe',
            new_name='GameTicTacToe',
        ),
    ]
