# Generated by Django 4.0.6 on 2022-07-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_game_othello_gameothello_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametictactoe',
            name='board',
        ),
        migrations.RemoveField(
            model_name='gametictactoe',
            name='date_updated',
        ),
    ]
