# Generated by Django 4.0.6 on 2022-07-25 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_gametictactoe_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametictactoe',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='gametictactoe',
            name='player_o',
        ),
        migrations.RemoveField(
            model_name='gametictactoe',
            name='player_x',
        ),
        migrations.AddField(
            model_name='gameslist',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
