# Generated by Django 4.0.6 on 2022-08-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_gametictactoe_date_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameOthello',
        ),
        migrations.DeleteModel(
            name='GameTicTacToe',
        ),
    ]
